# Generated by Django 6.0.4 on 2026-05-03 19:11

import habits.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.PositiveIntegerField(
                default=120,
                validators=[habits.validators.validate_duration],
                verbose_name="Время на выполнение (в секундах)",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[habits.validators.validate_periodicity],
                verbose_name="Периодичность (в днях)",
            ),
        ),
    ]
